frontend/urls.py
from django.urls import path
from .views import HomeView, DetailToursView, TourListView, HotelListView, QuestionListView, UzbekistanTourListView, \
    CountryListView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # path('about-us/', AboutUsView.as_view(), name='about-us'),
    # path('news/', NewsView.as_view(), name='news'),
    path('tour/<int:pk>', DetailToursView.as_view(), name='tour-detail'),
    path('tours/', TourListView.as_view(), name='tour-list'),
    path('uzbekistan-tours/', UzbekistanTourListView.as_view(), name='uzbekistan-tour-list'),
    path('hotels/', HotelListView.as_view(), name='hotel-list'),
    path('questions/', QuestionListView.as_view(), name='question-list'),
    path('country/', CountryListView.as_view(), name='country-list')
]

travelhub/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from travelhub import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('frontend.urls')),
)

core/models.py
from django.core.exceptions import ValidationError
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

from site_management.models import SingletonModel


class Region(models.Model):
    title = models.CharField(
        verbose_name='Название региона',
        max_length=255
    )
    icon = models.FileField(
        verbose_name='Иконка',
        upload_to='country_icons/'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'


class Country(models.Model):
    region = models.ForeignKey(
        to=Region,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Регион',
        related_name='countries'
    )
    title = models.CharField(
        verbose_name='Название страны',
        max_length=255
    )
    icon = models.FileField(
        verbose_name='Иконка',
        upload_to='country_icons/'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class From(models.Model):
    title = models.CharField(
        verbose_name='Название города',
        max_length=255
    )
    country = models.ForeignKey(
        to=Country,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Страна',
        related_name='froms'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Откуда (Самарканд, Ташкент)'
        verbose_name_plural = 'Откуда (Самарканд, Ташкент)'
        ordering = ['-title']


class To(models.Model):
    title = models.CharField(
        verbose_name='Название',
        max_length=255
    )
    country = models.ForeignKey(
        to=Country,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Страна',
        related_name='to'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Куда (Турция, Дубай)'
        verbose_name_plural = 'Куда (Турция, Дубай)'
        ordering = ['-title']


class Airline(models.Model):
    title = models.CharField(
        verbose_name='Название авиалинии',
        max_length=255
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Авиалиния'
        verbose_name_plural = 'Авиалинии'


class Tour(models.Model):
    class Cuurency(models.TextChoices):
        summ = 'sum', 'Сум'
        usd = 'usd', 'Доллар'

    class People(models.IntegerChoices):
        one = 1, '1'
        two = 2, '2'
        three = 3, '3'
        four = 4, '4'

    class Transfer(models.TextChoices):
        group = 'group', 'Групповой'
        individual = 'individual', 'Индивидуальный'

    face_image = models.ImageField(
        verbose_name='Главная фотография',
        upload_to='face_images/'
    )
    global_title = models.CharField(
        verbose_name='Главное название',
        max_length=255
    )
    mini_title = models.CharField(
        verbose_name='Второстепенное название/Мини описание',
        max_length=255,
        blank=True,
        null=True
    )
    created = models.DateTimeField(
        verbose_name='Создано',
        auto_now_add=True
    )
    currency = models.CharField(
        verbose_name='Валюта',
        max_length=255,
        choices=Cuurency.choices,
        default='usd'
    )
    start_sum = models.FloatField(
        verbose_name='От (начальная цена)',
        default=0,
        null=True,
        blank=True
    )
    amount = models.FloatField(
        verbose_name='Общая стоимость',
        default=0,
        null=True,
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name='Активен ?',
        default=True
    )
    is_hot = models.BooleanField(
        verbose_name='Популярен ?',
        default=False
    )
    froms = models.ForeignKey(
        verbose_name='Откуда',
        to=From,
        on_delete=models.SET_NULL,
        null=True
    )
    to = models.ForeignKey(
        verbose_name='Куда',
        to=To,
        on_delete=models.SET_NULL,
        null=True
    )
    start_date = models.DateField(
        verbose_name='Дата начала',
        default=timezone.now(),
        null=True
    )
    end_date = models.DateField(
        verbose_name='Дата конца',
        default=timezone.now(),
        null=True
    )
    transfer = models.CharField(
        verbose_name='Трансфер',
        max_length=255,
        choices=Transfer.choices
    )
    airline = models.ForeignKey(
        to=Airline,
        verbose_name='Авиалиния',
        on_delete=models.SET_NULL,
        null=True
    )
    have_a_car = models.BooleanField(
        verbose_name='Аренда машины ?',
        default=False
    )
    have_a_boat = models.BooleanField(
        verbose_name='Аренда лодки ?',
        default=False
    )
    content = RichTextUploadingField(
        verbose_name='Контент',
        null=True
    )
    in_uzbekistan = models.BooleanField(
        verbose_name='По Узбекистану ?',
        default=False
    )
    tourists = models.SmallIntegerField(
        verbose_name='Туристы',
        choices=People.choices,
        null=True
    )

    def __str__(self):
        return self.global_title

    def clean(self):
        if self.amount and self.start_sum:
            raise ValidationError('Не может быть цены от и общей суммы в одном туре')

    class Meta:
        verbose_name = 'Тур'
        verbose_name_plural = 'Туры'


class Day(models.Model):
    tour = models.ForeignKey(
        to=Tour,
        verbose_name='Тур',
        related_name='days',
        on_delete=models.CASCADE
    )
    number = models.SmallIntegerField(
        verbose_name='День',
        default=1,
    )
    content = RichTextUploadingField(
        verbose_name='Контент'
    )

    def __str__(self):
        return f"{self.tour.global_title} | Day {self.number}"

    class Meta:
        verbose_name = 'День'
        verbose_name_plural = 'Дни'


class TourImage(models.Model):
    tour = models.ForeignKey(
        to=Tour,
        verbose_name='Тур',
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(
        verbose_name='Фотография',
        upload_to='tour_images/'
    )

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = 'Фотография тура'
        verbose_name_plural = 'Фотографии туров'


class Slider(models.Model):
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='slider_image/'
    )

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = 'Слайдер'
        verbose_name_plural = 'Слайдер'


class HotelTo(models.Model):
    title = models.CharField(
        verbose_name='Название города',
        max_length=255
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Города (месторасположение для отелей)'
        verbose_name_plural = 'Города (месторасположение для отелей)'


class Hotel(models.Model):
    class People(models.IntegerChoices):
        one = 1, '1'
        two = 2, '2'
        three = 3, '3'
        four = 4, '4'

    to = models.ForeignKey(
        HotelTo,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Куда'
    )
    start_date = models.DateField(
        verbose_name='Дата начала',
        default=timezone.now(),
        null=True
    )
    end_date = models.DateField(
        verbose_name='Дата конца',
        default=timezone.now(),
        null=True
    )
    people_count = models.SmallIntegerField(
        verbose_name='Количество посетителей',
        choices=People.choices
    )
    title = models.CharField(
        verbose_name='Название отеля',
        max_length=255
    )
    amount = models.IntegerField(
        verbose_name='Цена',
        default=0
    )
    address = models.CharField(
        verbose_name='Адресс',
        max_length=255
    )
    image = models.ImageField(
        verbose_name='Фотография',
        upload_to='hotels/'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Отель'
        verbose_name_plural = 'Отели'


class Question(models.Model):
    title = models.CharField(
        verbose_name='Заголовок',
        max_length=255
    )
    content = models.TextField(
        verbose_name='Контент'
    )
    image = models.ImageField(
        verbose_name='Фотография'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Памятка для туристов'
        verbose_name_plural = 'Памятки для туристов'

templates/cards.html
{% extends 'layout/base.html' %}
{% load static i18n %}

{% block content %}
    <!-- Page Title start -->
    <div class="pageTitle">
        <div class="container page-container">
{#            <h1 class="page-heading" style="">{% translate 'Страны' %}</h1>#}
        </div>
        <div class="page-img ibg">
            <img src="{{ header.image.url }}" alt="">
        </div>
        <div class="overlay"></div>
    </div>
    <!-- Page Title End -->

    <div class="innercms">
        <div class="container">

            <!-- Blog start -->
            <div class="row blogList custom-row">
                {% for card in cards %}
                    <div class="col-lg-4 col-md-4 col-sm-6 custom-card">
                        <div class="card post-header">
                            <img src="{{ card.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="">{{ card.title }}</a>
                                </h4>
                                <p class="card-text">{{ card.content }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/country.html
{% extends 'layout/base.html' %}
{% load static i18n %}
{% block content %}
    <div class="pageTitle">
        <div class="container page-container">
{#            <h1 class="page-heading" style="">{% translate 'Страны' %}</h1>#}
        </div>
        <div class="page-img ibg">
            <img src="{{ header.image.url }}" alt="">
        </div>
        <div class="overlay"></div>
    </div>
    <div class="wrapper">
        <div class="taglinewrap">
            <div class="container">
                <div class="country">
                    <h2 class="country__title">{% translate 'Страны' %}</h2>
                    {% for region in regions %}
                        <a href="{% url 'tour-list' %}?region={{ region.id }}">
                            <div class="country-continents">
                                <div class="country-continents__image">
                                    <img src="{{ region.icon.url }}" alt="">
                                </div>
                                <div class="country-continents__text">{{ region.title }}</div>
                            </div>
                        </a>
                        <div class="row country-row">
                            <div class="col-md-12 col-sm-12 col-c">
                                {% for country in region.countries.all %}
                                    <div class="country-item">
                                        <a class="country-item__link" href="{% url 'tour-list' %}?to={{ country.id }}">
                                            <div class="country-item__image">
                                                <img src="{{ country.icon.url }}" alt="">
                                            </div>
                                            <div class="country-item__text">
                                                {{ country.title }}
                                            </div>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/hotels.html
{% extends 'layout/base.html' %}
{% load i18n poll_extras %}
{% block content %}
    <div class="pageTitle">
        <div class="container page-container">
            {#            <h1 class="page-heading" style="">{% translate 'Страны' %}</h1>#}
        </div>
        <div class="page-img ibg">
            <img src="{{ header.image.url }}" alt="">
        </div>
        <div class="overlay"></div>
    </div>

    <div class="innercms">
        <div class="container">

            <!-- Blog start -->
            <div class="row">
                <div class="col-md-8">
                    <!-- Blog List start -->
                    <div class="blogWraper">
                        <ul class="blogList">
                            {% for hotel in hotels %}
                                <li>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <div class="postimg"><img src="{{ hotel.image.url }}"
                                                                      alt="Tour Image {{ forloop.counter }}"></div>
                                        </div>
                                        <div class="col-md-7">
                                            <div class="post-header">
                                                <h4><a>{{ hotel.title }}</a></h4>
                                                <div class="postmeta">
                                                    <span>{{ hotel.to }} </span>
                                                </div>
                                                <div class="date"><i class="fa fa-calendar" aria-hidden="true"></i>
                                                    2 {% translate 'Ночи' %} {{ hotel.people_count }}
                                                </div>
                                            </div>
                                            <p>{{ hotel.address }}</p>
                                            <a class="readmore"
                                               href="">{% translate 'Перейти' %}<i
                                                    class="fa fa-caret-right"
                                                    aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- Pagination -->
                    <div class="pagiWrap">
                        <nav aria-label="Page navigation" class="pagiwrap">
                            <ul class="pagination justify-content-center">

                                {% for page in  page_obj.paginator.page_range %}
                                    <li class="page-item {% if page_obj.number == page %}active{% endif %}"><a
                                            class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}

                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-4">
                    <!-- Side Bar -->
                    <div class="sidebar">
                        <!-- Search -->
                        <div class="widget">
                            <h5 class="widget-title">{% translate 'Найти' %}</h5>
                            <div class="search">
                                <form method="get">
                                    <input type="text" class="form-control" placeholder="Найти" name="search"
                                           value="{% if search %}{{ search }}{% endif %}">
                                    <button type="submit" class="btn"><i class="fa fa-search"></i></button>
                                </form>
                            </div>
                        </div>
                        <!-- Categories -->

                        <div class="widget">

                            <h5 class="widget-title">{% translate 'Найти по городу' %}</h5>

                            <ul class="categories">
                                {% for city in hotel_to %}
                                    <li><a href="{% url 'tour-list' %}?to={{ city.id }}">{{ city.title }}</a></li>
                                {% endfor %}
                            </ul>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/tour-detail.html
{% extends 'layout/base.html' %}
{% load i18n static %}
{% block content %}

    <div class="innercms">
        <div class="container">

            <!-- Blog start -->
            <div class="row">
                <div class="col-md-12">
                    <!-- Blog List start -->
                    <div class="blogWraper">
                        <div class="blogList blogdetailbox">
                            <div class="postimg"><img src="{{ tour.face_image.url }}" alt="Blog Title"></div>
                            <div class="post-header margin-top30">
                                <h4><a>{{ tour.global_title }}</a></h4>
                                <div class="postmeta" style="color: black; font-size: 20px;">
                                    {% translate 'Дата начала' %}: <a>  {{ tour.start_date }}</a>
                                    <br>
                                    <br>
                                    {% translate 'Дата конца' %}: <a>  {{ tour.end_date }}</a>
                                    <br>
                                    <br>
                                    {% translate 'Авиалиния' %}: <a>  {{ tour.airline }}</a>
                                    <br>
                                    <br>
                                    {% translate 'Откуда' %}: <a>  {{ tour.froms }}</a>
                                    <br>
                                    <br>
                                    {% translate 'Куда' %}: <a>  {{ tour.to }}</a>
                                    <br>
                                    <br>
                                    {% translate 'Трансфер' %}: <a>  {{ tour.get_transfer_display }}</a>
                                </div>
                            </div>

                            <br>
                            <div style="color: black">{{ tour.content|safe }} </div>

                            {% for day in tour.days.all %}
                                <p>
                                <h2>{% translate 'День' %} {{ day.number }}</h2>
                                {{ day.content|safe }}
                                </p>
                            {% endfor %}



                            {#                            <blockquote class="text-left-align">#}
                            {#                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu nulla eget nisl#}
                            {#                                    dapibus finibus. Maecenas quis sem vel neque rhoncus dignissim. Ut et eros rhoncus,#}
                            {#                                    gravida tellus auctor, lobortis diam. In eu porta purus, sit amet pulvinar eros.#}
                            {#                                    Cras accumsan dignissim convallis. Curabitur aliquam efficitur diam ac pellentesque.#}
                            {#                                    Fusce ac leo est.</p>#}
                            {#                                <span class="author-name"> <a href="tour-detail.html#.">Jhon Deneairo</a></span>#}
                            {#                            </blockquote>#}


                            {#                            <ul class="media-list">#}
                            {#                                <!-- COMMENTS -->#}
                            {#                                <li class="media">#}
                            {#                                    <div class="media-left"><a href="tour-detail.html#."> <img#}
                            {#                                            class="media-object img-responsive" src="images/coment-avatar-1.jpg" alt="">#}
                            {#                                        <br>#}
                            {#                                    </a></div>#}
                            {#                                    <div class="media-body">#}
                            {#                                        <h6 class="media-heading">Larsen Mortin<span> Dec 10, 2016 - 12.00 AM</span>#}
                            {#                                        </h6>#}
                            {#                                        <p>You would see the biggest gift would be from me and the card attached would#}
                            {#                                            say thank you for being a friend! Doin' it our way. Nothin's gonna turn us#}
                            {#                                            back now. Straight ahead. </p>#}
                            {#                                        <a href="tour-detail.html#." class="btn btn-yellow raply"><i class="fa fa-reply"#}
                            {#                                                                                                     aria-hidden="true"></i></a>#}
                            {#                                    </div>#}
                            {#                                </li>#}
                            {##}
                            {#                                <!-- COMMENTS -->#}
                            {#                                <li class="media margin-left80">#}
                            {#                                    <div class="media-left"><a href="tour-detail.html#."> <img#}
                            {#                                            class="media-object img-responsive" src="images/coment-avatar-2.jpg"#}
                            {#                                            alt="..."> </a></div>#}
                            {#                                    <div class="media-body">#}
                            {#                                        <h6 class="media-heading">Jhon Kennadi <span> Dec 10, 2016 - 12.00 AM</span>#}
                            {#                                        </h6>#}
                            {#                                        <p>Taque ipsa quae abe illo inventore veritatis et quasi architecto beatae vitae#}
                            {#                                            dicta sunt explicabo nemosala enim ipsam volupitatem quia voluptas sit#}
                            {#                                            aspernatur aut odit.</p>#}
                            {#                                        <a href="tour-detail.html#." class="btn btn-yellow raply"><i class="fa fa-reply"#}
                            {#                                                                                                     aria-hidden="true"></i></a>#}
                            {#                                    </div>#}
                            {#                                </li>#}
                            {#                                <!-- COMMENTS -->#}
                            {#                                <li class="media margin-left80">#}
                            {#                                    <div class="media-left"><a href="tour-detail.html#."> <img#}
                            {#                                            class="media-object img-responsive" src="images/coment-avatar-4.jpg"#}
                            {#                                            alt="..."> </a></div>#}
                            {#                                    <div class="media-body">#}
                            {#                                        <h6 class="media-heading">Jhon Kennadi <span> Dec 10, 2016 - 12.00 AM</span>#}
                            {#                                        </h6>#}
                            {#                                        <p>Taque ipsa quae abe illo inventore veritatis et quasi architecto beatae vitae#}
                            {#                                            dicta sunt explicabo nemosala enim ipsam volupitatem quia voluptas sit#}
                            {#                                            aspernatur aut odit.</p>#}
                            {#                                        <a href="tour-detail.html#." class="btn btn-yellow raply"><i class="fa fa-reply"#}
                            {#                                                                                                     aria-hidden="true"></i></a>#}
                            {#                                    </div>#}
                            {#                                </li>#}
                            {##}
                            {#                                <!-- COMMENTS -->#}
                            {#                                <li class="media">#}
                            {#                                    <div class="media-left"><a href="tour-detail.html#."> <img#}
                            {#                                            class="media-object img-responsive" src="images/coment-avatar-3.jpg"#}
                            {#                                            alt="..."> </a></div>#}
                            {#                                    <div class="media-body">#}
                            {#                                        <h6 class="media-heading">Rock Lancer <span>Dec 10, 2016 - 12.00 AM</span></h6>#}
                            {#                                        <p>Taque ipsa quae abe illo inventore veritatis et quasi architecto beatae vitae#}
                            {#                                            dicta sunt explicabo nemosala enim ipsam volupitatem quia voluptas sit#}
                            {#                                            aspernatur aut odit aut fugite.</p>#}
                            {#                                        <a href="tour-detail.html#." class="btn btn-yellow raply"><i class="fa fa-reply"#}
                            {#                                                                                                     aria-hidden="true"></i></a>#}
                            {#                                    </div>#}
                            {#                                </li>#}
                            {#                            </ul>#}


                            <div class="image-carousel">
                                {% for image in tour.images.all %}
                                    <div class="image-carousel__item item-carousel">
                                        <img src="{{ image.image.url }}" alt="" class="item-carousel__image">
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="comments margin-top30">
                                <!-- LEAVE COMMENTS -->
                                <div class="commnetsfrm">
                                    <h4>{% translate 'Свяжитесь с нами !' %}</h4>
                                    <form method="post" action="{% url 'tour-detail' tour.id %}">
                                        {% csrf_token %}
                                        <ul class="row">
                                            <li class="col-sm-6">
                                                <label>
                                                    <input type="text" class="form-control" name="name"
                                                           placeholder="{% translate 'Имя' %}">
                                                </label>
                                            </li>
                                            <li class="col-sm-6">
                                                <label>
                                                    <input type="text" class="form-control" name="name"
                                                           placeholder="{% translate 'Email' %}">
                                                </label>
                                            </li>
                                            <li class="col-sm-12">
                                                <label>
                                                <textarea class="form-control"
                                                          placeholder="{% translate 'Ваше сообщение' %}"></textarea>
                                                </label>
                                            </li>
                                            <li class="col-sm-12">
                                                <button type="submit"
                                                        class="btn margin-top-20">{% translate 'Отправить' %}</button>
                                            </li>
                                        </ul>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}